#logging:
#  level:
#    com.adverity.demo.simpledatawarehouse: TRACE
#    org.hibernate.tool.hbm2ddl: DEBUG

spring:

  jpa:
    database: default # auto detect dialects with this
    generate-ddl: false
    show-sql: false

  data:
    rest:
      basePath: /warehouse/rest/
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

appengine:
    deploy:
      projectId: GCLOUD_CONFIG

server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto