runtime: java11
entrypoint: java -jar simple-data-warehouse-0.0.1-SNAPSHOT.war --server.port=$PORT
runtime_config:
  jdk: openjdk11
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
